# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings


# Organizer Info


# Head
metaKeywords: "event"


# Documents



# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/features/", text: "Features"}
 - {permalink: "/oteam/", text: "Teamnew"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/communities/", text: "Communities"}
 - {permalink: "/hackathon/", text: "Hackathon"}
 - {permalink: "/blog/", text: "Blog"}


# Hero Block
heroImage: "hero.jpg"
heroTitle: "YOUR <typeout> in one place"
eventDate: "Your community"
typeoutTextValues: '"", "online community", "groups", "TV channel", "loyalty"'
typeoutFallback: "Season"
heroButtons:
 - {link: "http://corp.vot.expert", text: "Попробуй бесплатно!"}
 
